name: OCI ARM Host Capacity

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Dump autoloader
        run: composer dump-autoload

      - name: Create .env file
        run: |
          echo "OCI_USER_OCID=${{ secrets.OCI_USER_OCID }}" >> .env
          echo "OCI_USER_ID=${{ secrets.OCI_USER_OCID }}" >> .env
          echo "OCI_TENANCY_OCID=${{ secrets.OCI_TENANCY_OCID }}" >> .env
          echo "OCI_FINGERPRINT=${{ secrets.OCI_FINGERPRINT }}" >> .env
          echo "OCI_REGION=${{ secrets.OCI_REGION }}" >> .env
          echo "OCI_PRIVATE_KEY=\"${{ secrets.OCI_PRIVATE_KEY }}\"" >> .env
      - name: Run OCI Capacity Script
        run: php index.php
